version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.7.2
  heroku: circleci/heroku@2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
      
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: lolfoollor/node-app-for-devops
      - docker/push:
          image: lolfoollor/node-app-for-devops
    
  deploy:
    executor: heroku/default
    steps:
      - setup_remote_docker
      - heroku/install
      - checkout
      - run:
          name: Heroku Container Push
          command: |
            heroku container:login
            heroku stack:set container -a lolfoollor-su-devops
            heroku container:push web -a lolfoollor-su-devops
            heroku container:release web -a lolfoollor-su-devops
        
workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - release
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - release
      - build-and-push:
          filters:
            branches:
              only:
                - release
      - deploy:
          filters:
            branches:
              only:
                - release