version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@latest

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
      
  build-and-push:
    docker:
      - image: cimg/docker:latest
    steps:
      - checkout
      - docker/login:
          registry: docker-hub
          token: $DOCKER_TOKEN
      - run: |
          echo "Building Docker image..."
          docker build -t lolfoollor/node-app-for-devops:latest .
      - docker/push:
          image: lolfoollor/node-app-for-devops:latest
        
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push